import { Activity, CircleDollarSign, FileClock, Headphones, LayoutDashboard, LogOut, Settings, Store, Users, X, Bell } from "lucide-react";
import { NavLink } from "react-router-dom";

interface Props { collapsed: boolean; mobileOpen: boolean; onToggle: () => void; onCloseMobile: () => void; onLogout: () => void; }
const groups = [
  { label: "Overview", items: [{ label: "Dashboard", icon: LayoutDashboard, to: "/admin/dashboard" }] },
  { label: "Management", items: [{ label: "Retailers", icon: Store, to: "/admin/retailers" }, { label: "Transactions", icon: Activity, to: "/admin/transactions" }, { label: "Customers", icon: Users, to: "/admin/customers" }] },
  { label: "Configuration", items: [{ label: "CMS Configuration", icon: Settings, to: "/admin/cms" }, { label: "Commissions", icon: CircleDollarSign, to: "/admin/commissions" }, { label: "Banners", icon: Bell, to: "/admin/banners" }] },
  { label: "System", items: [{ label: "Audit Logs", icon: FileClock, to: "/admin/audit-logs" }, { label: "Support", icon: Headphones, to: "/admin/support" }] },
];

export default function AdminSidebar({ collapsed, mobileOpen, onToggle, onCloseMobile, onLogout }: Props) {
  return <>
    {mobileOpen && <button type="button" aria-label="Close navigation" onClick={onCloseMobile} className="fixed inset-0 z-40 bg-slate-950/35 lg:hidden" />}
    <aside className={`fixed inset-y-0 left-0 z-50 flex w-[280px] flex-col border-r border-slate-200 bg-white transition-transform lg:static lg:z-auto lg:translate-x-0 ${collapsed ? "lg:w-[86px]" : "lg:w-[256px]"} ${mobileOpen ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex h-20 items-center justify-between border-b border-slate-100 px-5"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl shadow-sm p-1"><img src="/happy-favicon.jpeg" alt="Happy Pay Logo" className="h-full w-full rounded-lg object-contain bg-white" /></div><div className={collapsed ? "hidden" : "block"}><p className="font-extrabold text-slate-900">HappyPay</p><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#315bd1]">Super Admin</p></div></div><button type="button" onClick={onCloseMobile} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 lg:hidden" aria-label="Close sidebar"><X className="h-5 w-5" /></button></div>
      <nav className="custom-scrollbar flex-1 overflow-y-auto px-3 py-5">{groups.map((group) => <div key={group.label} className="mb-6"><p className={`mb-2 px-3 text-[10px] font-bold uppercase tracking-[0.16em] text-slate-400 ${collapsed ? "lg:hidden" : ""}`}>{group.label}</p>{group.items.map((item) => { const Icon = item.icon; return item.to ? <NavLink key={item.label} to={item.to} onClick={onCloseMobile} title={collapsed ? item.label : undefined} className={({ isActive }) => `mb-1 flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold transition ${isActive ? "bg-[#eef2ff] text-[#315bd1]" : "text-slate-600 hover:bg-slate-50 hover:text-slate-900"} ${collapsed ? "lg:justify-center" : ""}`}><Icon className="h-[18px] w-[18px] shrink-0" /><span className={collapsed ? "lg:hidden" : ""}>{item.label}</span></NavLink> : <button key={item.label} type="button" disabled title={collapsed ? `${item.label} (coming soon)` : undefined} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-semibold text-slate-400 ${collapsed ? "lg:justify-center" : ""}`}><Icon className="h-[18px] w-[18px] shrink-0" /><span className={collapsed ? "lg:hidden" : ""}>{item.label}</span></button>; })}</div>)}</nav>
      <div className="border-t border-slate-100 p-3"><div className={`mb-2 flex items-center gap-3 rounded-xl bg-slate-50 p-3 ${collapsed ? "lg:justify-center" : ""}`}><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-[#dbe4ff] text-xs font-bold text-[#315bd1]">SA</div><div className={collapsed ? "lg:hidden" : ""}><p className="text-xs font-bold text-slate-900">Super Admin</p><p className="text-[11px] text-slate-500">Administrator</p></div></div><button type="button" onClick={onLogout} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-slate-500 hover:bg-rose-50 hover:text-rose-600 ${collapsed ? "lg:justify-center" : ""}`}><LogOut className="h-[18px] w-[18px]" /><span className={collapsed ? "lg:hidden" : ""}>Logout</span></button></div>
      <button type="button" onClick={onToggle} className="absolute -right-3 top-24 hidden h-7 w-7 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-500 shadow-sm lg:flex" aria-label="Toggle sidebar">{collapsed ? "›" : "‹"}</button>
    </aside>
  </>;
}
